[package]
name = "chip8rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.23.0"
mockall_double = "0.3.0"
rand = "0.8.5"

[dev-dependencies]
mockall = "0.11.0"
test-case = "2.0.2"
